### PR TITLE
feat: add skip-empty-files flag

### LINKED ISSUE #6: Passing an empty file throws error
`./dist/assets/home.8e212dc3.css` is empty and has `0 bytes`.

```
> brotli-cli compress --glob './dist/*.html' --glob './dist/*.ico'  --glob './dist/assets/*.css' --glob './dist/assets/*.js'

Error happened during compression process, the process is stopped.
File: ./dist/assets/home.8e212dc3.css
TypeError: Empty response returned from brotli
    at /Users/xo/code/OmgImAlexis/siteli.st/client/node_modules/brotli-cli/dist/index.js:146:27
    at async Promise.all (index 7)
    at async Object.handler (/Users/xo/code/OmgImAlexis/siteli.st/client/node_modules/brotli-cli/dist/index.js:133:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.0 compress-assets: `brotli-cli compress --glob './dist/*.html' --glob './dist/*.ico'  --glob './dist/assets/*.css' --glob './dist/assets/*.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.0.0 compress-assets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xo/.npm/_logs/2021-07-11T02_23_18_003Z-debug.log
```

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Feel free to push commits to this if I missed something.

Closes #6

### CODE REVIEW

**Comment by dzek69** [comment]
Hello,
Thanks for your contribution 👍🏻 

I think we should treat this like a bug - it shouldn't be considered an error when brotli returns empty result from empty source.

IIRC I added this check, because `brotli` sometimes returns empty result instead of throwing an error, but I forgot about possible empty sources.

Can you please update your code (ideally - replace the commit, instead of adding another one) to just allow empty result from empty source, without triggering an error, without need for the flag?

Also please update CHANGELOG with description of the fix and bump package.json version to 1.0.3 (I do that manually) and I will immediately release a new version after merging your changes.

Thanks again!

**Comment by dzek69** [comment]
@OmgImAlexis ping :) if you are busy then i'm gonna implement those changes over the weekend

**Comment by OmgImAlexis** [comment]
> @OmgImAlexis ping :) if you are busy then i'm gonna implement those changes over the weekend

If I don’t get to it by the end of the week feel free to add the commits to this branch. It should have maintainer push enabled.

**Comment by dzek69** [comment]
Thanks again for reporting and suggesting a fix.

I skipped your commit as a whole, because none of these lines were used in the final solution to this bug.

Bug is fixed with 1.0.3 version

**Pull request closed without merging**
